### ISSUE TITLE
Call to a member function getProperties() on boolean

### ISSUE THREAD

**Issue by elodie-nazaret** [algolia/AlgoliaSearchBundle#33] opened 2015-12-01 13:47 UTC
Hello,

After adding @Algolia\Attribute annotation on a property with a ManyToOne assocation I tried to index my entity using `app/console algolia:reindex AppBundle:Project`.

But this command returns me an error :

`PHP Fatal error:  Call to a member function getProperties() on boolean in /home/elodie/workspace/my-project/vendor/algolia/algolia-search-bundle/Indexer/Indexer.php on line 407`

Here is my entity Project : 
https://gist.github.com/elodie-nazaret/acc9765039385ec8f9aa

And there are versions I use :
```json
"symfony/symfony": "2.8.*@dev",
"doctrine/orm": "^2.4.8",
"doctrine/doctrine-bundle": "~1.4",
"algolia/algolia-search-bundle": "^1.0"
```

Related to issue #27

**Comment by maxiloc** [comment] 2015-12-01 13:57
Ok that's weird, let's try to narrow it down:

Can you try without this line => https://gist.github.com/elodie-nazaret/acc9765039385ec8f9aa#file-project-php-L16

Then if it's not working, can you also try without "OneToMany" attributes ?

**Comment by elodie-nazaret** [comment] 2015-12-01 14:11
I removed `@Algolia\Index()` but it did not work either.
When I delete all `@Algolia\Attribute` that are on OneToMany properties it works.

**Comment by maxiloc** [comment] 2015-12-01 14:11
Ok cool, I will look into it asap

**Comment by elodie-nazaret** [comment] 2015-12-01 14:12
Thank you

**Comment by tristanbes** [comment] 2015-12-02 12:49
ping @maxiloc do you have any ETA so we can adapt for this ingoing project that has a close shipping date ?

**Comment by maxiloc** [comment] 2015-12-02 12:50
I starting right now, so probably today

**Comment by maxiloc** [comment] 2015-12-02 14:05
I am still not able to reproduce the issue. I found another one related to oneToMany that I fixed (https://github.com/algolia/AlgoliaSearchBundle/commit/241bb848e03e2f62408d66af3c293f3767f87e9e)
It might also fix this one.

@elodie-nazaret @tristanbes Can you try with "algolia/algolia-search-bundle": "dev-master" in your composer.json and tell me if you still encounter the issue.

I also suspect some symfony/doctrine/composer cache, can you make sure you cleaned it before testing

**Comment by elodie-nazaret** [comment] 2015-12-02 15:25
I tried with "algolia/algolia-search-bundle": "dev-master" but it returns me the same error.

**Comment by tristanbes** [comment] 2015-12-02 15:45
```
I am still not able to reproduce the issue.
```

Can you try to reproduce it inside a brand new Symfony2.8 standard edition please ? https://github.com/symfony/symfony-standard/tree/2.8
If I had the problem inside my other project (in 2.4) and this happens again in (2.8) the issue must be real.

**Comment by maxiloc** [comment] 2015-12-02 16:01
I was on 2.6, tried on a clean 2.8 and it still working.
Any debugging you could do to could really help to find where it's coming from, in the meantime I will continue investigating

**Comment by maxiloc** [comment] 2015-12-03 10:37
Ok I managed to reproduce. The issue comes when a relation is an Algolia\Attribute but this relation class does not have any Algolia\Attribute.

**Comment by maxiloc** [comment] 2015-12-03 10:47
@tristanbes @elodie-nazaret There is no fix for this, what I did is throw an more explicit error so that it's easier to understand why it's failing

**Comment by tristanbes** [comment] 2015-12-04 22:27
Sure, maybe you can elaborate on what we were doing wrong ? And add it in the documentation of the bundle so this won't happen again.

**Comment by maxiloc** [comment] 2015-12-07 09:42
Yes when you are indexing a model in Algolia that have a relation the bundle will load this relation and get all indexable algolia attribute in an array and append it to the initial model object.

For example:
```
class Post
{
    private $title; // Algolia attribute
    private $content; // Algolia attribute
    private $author // Relation to the Author model + Algolia attribute
}
```

If the Author model don't have any Algolia attribute your were getting a non explicit error. To fix it you need to put Author::$name as an Algolia attribute so that the final record looks like : 

```
{
  "title": "some title"
  "content": "some content"
  "author": {
     "name": "some name"
  }
} 
```

Does that makes sense ?

**Comment by tristanbes** [comment] 2015-12-07 10:14
yeap. Thanks. will close the issue once we test this and see if we get rid of this error. :-)

**Comment by elodie-nazaret** [comment] 2015-12-07 10:33
I tried to add @Algolia\Attribute() in my entity linked but it seems that it doesn't work either... I cleared cache and restarted php before.
There is a part of my Entity Project : 
```php
/**
 * Class Project
 *
 * @ORM\Entity(repositoryClass="AppBundle\Entity\ProjectRepository")
 * @ORM\Table(name="project")
 * @Algolia\Index()
 */
class Project
{
    /**
     * @var string
     *
     * @ORM\Column(type="string", name="realisation_name"))
     * @Algolia\Attribute()
     */
    private $realisationName;

    /**
     * @var RegionalManagement
     *
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\RegionalManagement")
     * @ORM\JoinColumn(name="regional_management_id", referencedColumnName="id")
     * @Algolia\Attribute()
     */
    private $regionalManagement;
}
```
And there is a part of my Entity RegionalManagement : 
```php
/**
 * Class RegionalManagement
 *
 * @ORM\Entity()
 * @ORM\Table(name="regional_management")
 */
class RegionalManagement
{
       /**
     * @var string
     *
     * @ORM\Column(type="string", name="label"))
     * @Algolia\Attribute()
     */
    private $label;
}
```
And when I tried to execute `app/console algolia:reindex AppBundle:Project`
It sends me the error : 
```
[Algolia\AlgoliaSearchBundle\Exception\NotAnAlgoliaEntity]                                                                                                             
Tried to index `regionalManagement` relation which is a `Proxies\__CG__\AppBundle\Entity\RegionalManagement` instance, which is not recognized as an entity to index.
```

Did I do something wrong?

**Comment by maxiloc** [comment] 2015-12-07 10:42
@elodie-nazaret Can you send me the full file of Project and RegionalManagement ?

**Comment by elodie-nazaret** [comment] 2015-12-07 10:47
Of course : 
Project : https://gist.github.com/elodie-nazaret/acc9765039385ec8f9aa
RegionalManagement : https://gist.github.com/elodie-nazaret/b8cb9a69dd472ee2bfdd

**Comment by maxiloc** [comment] 2015-12-07 11:11
@elodie-nazaret I fix a potential issue with proxies, can you try again with "dev-master"

**Comment by elodie-nazaret** [comment] 2015-12-07 11:30
I changed version to "dev-master", updated composer, cleared cache, restarted php but I still have the same error. I checked that I have your corrective.

**Comment by elodie-nazaret** [comment] 2015-12-07 14:26
ping @maxiloc Do you have an idea of why it still does not work ?

**Comment by maxiloc** [comment] 2015-12-07 14:27
Not yet I am not able to reproduce

**Comment by tristanbes** [comment] 2015-12-07 14:43
@maxiloc to be more convinient, i've invited you to the repo in order you to reproduce the issue if you'd like. I'll remove your rights in an hour or so.
```
git checkout feature/YP-2147
composer install
php app/console do:da:cr
php app/console do:sc:up --force
php app/console do:fi:lo
app/console algolia:reindex AppBundle:Project
```

**Comment by maxiloc** [comment] 2015-12-07 14:44
ok I'm checking that right now

**Comment by maxiloc** [comment] 2015-12-07 15:01
Ok I found it !! I am on the fix

**Comment by tristanbes** [comment] 2015-12-07 15:02
Great, thanks, ready to press `composer update` . ;-)

**Comment by maxiloc** [comment] 2015-12-07 15:33
@tristanbes @elodie-nazaret I pushed to master, it should be good. It was due to the doctrine proxies that were interfering in the indexing

**Closed** 2015-12-07 15:32 UTC

**Comment by maxiloc** [comment] 2015-12-07 15:33
If it is working for you I will tag a new version

**Comment by tristanbes** [comment] 2015-12-07 15:38
Thanks. :-) @elodie-nazaret will tell you if it's ok for tagging.

**Comment by elodie-nazaret** [comment] 2015-12-07 15:48
It works now !
Thanks you @maxiloc  :-)
