### ISSUE TITLE
Call to a member function getProperties() on a non-object 

### ISSUE THREAD

**Issue by tristanbes** [algolia/AlgoliaSearchBundle#27] opened 2015-10-04 09:52 UTC
Hi,

After adding `@Algolia\Attribute` annotation on my properties (protected properties) I tried to index my entity using `sf algolia:reindex GamerCertifiedCvBundle:Cv`

But that gives me: 

`PHP Fatal error:  Call to a member function getProperties() on a non-object in /Users/tbessoussa/workspace/seekteam/vendor/algolia/algolia-search-bundle/Indexer/Indexer.php on line 407`

`ldd(self::$indexSettings[$class]);`

<img width="825" alt="capture d ecran 2015-10-04 a 11 47 44" src="https://cloud.githubusercontent.com/assets/346010/10267256/d6302d56-6a8d-11e5-826a-f739ae8938a7.png">

Using `^1.0` version (1.0.8).
```json
"symfony/symfony": "2.6.*",
"doctrine/orm": "~2.2,>=2.2.3,<2.5",
"doctrine/dbal": "<2.5",
"doctrine/doctrine-bundle": "~1.2",
```

**Comment by maxiloc** [comment] 2015-11-06 13:02
@tristanbes Sorry for the late reply, Are you still experiencing the issue ?

**Comment by tristanbes** [comment] 2015-11-06 13:32
well i abandonned, but yeah each time i tried, facing this issue.

**Comment by maxiloc** [comment] 2015-11-06 13:52
Would you mind sending your class GamerCertifiedCvBundle:Cv

**Comment by tristanbes** [comment] 2015-11-06 13:58
https://gist.github.com/tristanbes/f43eb025dd11a7bf32d2 , please answer so i can remove the link after you saw it. It does not contain the Algolia annotation as i didn't kept them after I saw this was a dead end.

**Comment by maxiloc** [comment] 2015-11-06 14:03
Yes ok, I am done, I wanted to check annotations.
I am closing this as I am not able to reproduce it.
If you decide to give it another try and face the same issue you can reopen it, I will make sure to react on it quickly.

**Closed** 2015-11-06 15:03 UTC
